1\. **Reductions**

Given the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

   1. find the total mean
   2. find the mean for each row and column

In [1]:
import numpy as np

m = np.arange(12).reshape((3,4))
print(m)
mean_m = np.mean(m)
print('Mean of m:',mean_m)
mean_column = m.mean(0)
print('Mean of each column:', mean_column)
mean_row = m.mean(1)
print('Mean of each row:', mean_row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Mean of m: 5.5
Mean of each column: [4. 5. 6. 7.]
Mean of each row: [1.5 5.5 9.5]


2\. **Outer product**

Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

3\. **Matrix masking**

Create a $10 \times 6$ matrix of float random numbers, distributed between 0 and 3 according to a flat distribution.

After creating the matrix, set all entries $< 0.3$ to zero using a mask.

4\. **Trigonometric functions**

Use `np.linspace` to create an array of 100 numbers between $0$ and $2\pi$ (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the `sin` and `cos` functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the `sin` and `cos` functions and indicate graphically (with a line or a marker) where they are close

In [2]:
import numpy as np
import math

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

mylist = []
mylist.append(x[np.fabs(np.cos(x)-np.sin(x))<0.1])
print(mylist)
print(x[3])
print(x[1:len(x):3])
print(x[1:len(x):2])
print(x[::-1])

[array([7])]
3
[1 4 7]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


5\. **Matrices**

Create a matrix that shows the $10 \times 10$ multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [3]:
import numpy as np
mul_table = np.fromfunction(lambda i, j: (i+1)*(j+1), (10,10))
print(mul_table)

[mul_table[i][i+1] for i in range(9)]

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.  30.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.  40.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.  60.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.  70.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.  80.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.  90.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]]


[2.0, 6.0, 12.0, 20.0, 30.0, 42.0, 56.0, 72.0, 90.0]

6\. **Broadcasting**

Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles.

The corresponding positions in miles are: `0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448`

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [4]:
import numpy as np

cities = ['Chicago', 'Springfield', 'Saint-Louis', 'Tulsa', 'Oklahoma City', 'Amarillo', 'Santa Fe', 'Albuquerque', 'Flagstaff', 'Los Angeles']
pos = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])*1.60934

distances = np.array([abs(pos[i] - pos) for i in range(2,len(pos))])
distances 


array([[ 487.63002,  168.9807 ,    0.     ,  696.84422,  914.10512,
        1403.34448, 1886.14648, 1997.19094, 2591.0374 , 3452.0343 ],
       [1184.47424,  865.82492,  696.84422,    0.     ,  217.2609 ,
         706.50026, 1189.30226, 1300.34672, 1894.19318, 2755.19008],
       [1401.73514, 1083.08582,  914.10512,  217.2609 ,    0.     ,
         489.23936,  972.04136, 1083.08582, 1676.93228, 2537.92918],
       [1890.9745 , 1572.32518, 1403.34448,  706.50026,  489.23936,
           0.     ,  482.802  ,  593.84646, 1187.69292, 2048.68982],
       [2373.7765 , 2055.12718, 1886.14648, 1189.30226,  972.04136,
         482.802  ,    0.     ,  111.04446,  704.89092, 1565.88782],
       [2484.82096, 2166.17164, 1997.19094, 1300.34672, 1083.08582,
         593.84646,  111.04446,    0.     ,  593.84646, 1454.84336],
       [3078.66742, 2760.0181 , 2591.0374 , 1894.19318, 1676.93228,
        1187.69292,  704.89092,  593.84646,    0.     ,  860.9969 ],
       [3939.66432, 3621.015  , 3452.0343

7\. **Prime numbers sieve**

Compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).

  * Construct a shape (N,) boolean array, which is the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (with `timeit`); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [5]:
import numpy as np
import time
import math

def isPrime(x):
    if x <= 1:
        return False
    for i in range(2,x):
        if x%i==0:
            return False
    return True

t0 = time.time()
x = np.arange(1,99)
N = np.zeros_like(x, dtype=bool)

for j in range(len(x)):
    N[j] = isPrime(x[j])

numpy_N = np.array(N)
prime_num = x[N]
t1 = time.time()
print('Time taken to find the prime numbers up to 99:', t1-t0)


t2 = time.time()
N1 = np.array([True for i in range(len(x))])

for i in range(2, int(math.sqrt(len(x)))+1):
    if N1[i] == True:
        j = np.arange(i**2, len(x), i)
        N1[j] = False

prime_num_erato = np.where(N1)[0]
t3 = time.time()
print('Time taken to find the prime numbers up to 99 with Eratosthenes sieve:',t3-t2)


Time taken to find the prime numbers up to 99: 0.003940105438232422
Time taken to find the prime numbers up to 99 with Eratosthenes sieve: 0.0004432201385498047


8\. **Diffusion using random walk**

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of many random walkers after a given amount of time.

*Hint*: create a 2D array where each row represents a walker, and each column represents a time step.

  * Take 1000 walkers and let them walk for 200 steps
  * Use `randint` to create a 2D array of size $walkers \times steps$ with values -1 or 1
  * Calculate the walking distances for each walker (e.g. by summing the elements in each row)
  * Take the square of the previously-obtained array (element-wise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * **Optional**: plot the average distances ($\sqrt(distance^2)$) as a function of time (step)

In [26]:
import numpy.random as npr
import numpy as np

temp = npr.randint(2, size=(1000, 200))
print(temp)

#rd = np.zeros((1000,200))
#for i in range(1000):
#    for j in range(200):
#        if temp[i,j] == 0:
#            rd[i,j] = -1
#        else:
#            rd[i,j] = temp[i,j]


rd = np.array([temp[i, j] - 1 if temp[i,j] == 0 else temp[i,j] for i in range(1000) for j in range(200)])
rd = rd.reshape((1000,200))
print(rd)

walking_dist = np.array(temp.sum(axis=1))**2
walking_dist.size


[[1 1 0 ... 0 0 1]
 [1 0 1 ... 0 1 1]
 [0 1 0 ... 0 1 0]
 ...
 [1 1 1 ... 1 0 1]
 [0 1 0 ... 0 1 1]
 [1 0 0 ... 1 0 0]]
[[ 1  1 -1 ... -1 -1  1]
 [ 1 -1  1 ... -1  1  1]
 [-1  1 -1 ... -1  1 -1]
 ...
 [ 1  1  1 ...  1 -1  1]
 [-1  1 -1 ... -1  1  1]
 [ 1 -1 -1 ...  1 -1 -1]]


ValueError: cannot reshape array of size 1000 into shape (1000,200)